name: drupalnext-base
recipe: lagoon
config:
  flavor: drupal
  webroot: web
  compose:
    - docker-compose.lando.yml

events:
  post-start:
    - |
      if [ ! -d vendor ]; then
        echo "Running composer install..."
        composer install
      else
        echo "Vendor folder exists; skipping composer install."
      fi



